<% root_path='/tmp/kitchen' %>
<% @salt_versions = [
  ['stable', '2018.3.3']
] %>

driver:
  name: docker
  use_sudo: false
  privileged: true

platforms:
  - name: debian

provisioner:
  name: salt_solo
  is_file_root: true
  root_path: <%= root_path %>
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - .bundle
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
    - vendor
    - SaltGenResource.pyc
  state_top:
    base:
      '*':
        - tests.sandbox
  pillars:
    top.sls:
      base:
        '*':
          - kitchen
    kitchen.sls:
      kitchen:
        provisioner:
          root_path: <%= root_path %>

suites:
<% @salt_versions.each do |version| %>
  - name: '<%= version[1].gsub('.', '-') %>'
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 -p python-mock <%= version[0] %> <%= version[1] %>
<% end %>

verifier:
  name: shell
  remote_exec: false
  command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o LogLevel=ERROR -i ${KITCHEN_SSH_KEY} -p ${KITCHEN_PORT} ${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME} python2 <%= root_path %>/srv/salt/test.py
